"""empty message

Revision ID: a48498511d81
Revises: 6114ce643fd2
Create Date: 2020-11-15 12:32:51.001678

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a48498511d81'
down_revision = '6114ce643fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'auth_users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_users', type_='unique')
    op.drop_column('auth_users', 'email')
    # ### end Alembic commands ###
